apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: django-todo

spec:
  replicas: 3
  selector: 
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
        - name: django-ctr
          image: jatin7011/django-todo:latest
          ports:
            - containerPort: 8000
