apiVersion: v1
kind: Pod 
metadata: 
  name: django-todo
  namespace: django-app
spec:
  containers:
    - name: django-todo-ctr
      image: jatin7011/django-app:latest
      ports:
        - containerPort: 8001
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
